--REGION GET THE LSIT OF CASES BY TEAM AND FILENAME
SELECT distincT
       P.CASE_CNTR,    
       P.MMR_CASE,     
       P.TEAM_ASSIGNED, --STRAT, NM, CCT
       CASE WHEN P.TEAM_ASSIGNED = 'STRAT' THEN P.POOL_NUM||'_'||P.POOL_NAME||'_GAP_REPORT_'||P.MMR_CASE
                                           ELSE P.TEAM_ASSIGNED||'-'||P.MMR_CASE
       END AS FILE_NAME
 FROM MRGN_EU.PAL_RPA_test P
      JOIN  (SELECT MAX(INSRT_DT) INSRT_DT
             FROM MRGN_EU.PAL_RPA_test P
             )X ON P.INSRT_DT = X.INSRT_DT
                --AND P.TEAM_ASSIGNED = X.TEAM_ASSIGNED removed this line to eliminate strat cases when they had not been inserted on the same date with cct/NM cases
                ;--END REGION

------------------------------------------------------------
--4 FOR STRAT--
------------------------------------------------------------
--REGION var cost for excel 
SELECT  P.MMR_CASE,
        P.SYS_PLTFRM,
        P.BUS_PLTFRM,
        P.POOL_NUM,
        P.POOL_NAME,
        P.VENDOR_NAME,
        P.CURR_MCK_CONT,
        P.CURR_MFG_CONT,
        P.CURR_MFG_CONT_NAME,
        P.CURR_CONT_TYPE,
        P.VRCST_ORGN_SCR,
        P.VRCST_MCK_CONT,
        P.VRCST_MFG_CONT,  
        P.VAR_CST_CONT_NAME,
        P.VAR_CST_CONT_TYPE,
        P.VRCST_CONT_ATR_ELIG_FLG,
        P.VRCST_CONT_TIER_BASE_FLG,
        P.VRCST_GPO_NAME,
        P.GPO_COT,
        P.GPO_COT_NAME,
        P.PRMRY_GPO_FLAG,
        P.PRMRY_GPO_NAME,
        P.PRMRY_GPO_ID,
        P.GPO_MMBRSHP_ST,
        P.PRMRY_AFF_ST,
        P.RX_GPO_NAME,
        P.RX_GPO_ID,
        P.ACCT_OR_BILL_TO,
        P.ACCT_OR_BILL_TO_NAME,
        P.SHIP_TO,
        P.ST_NAME,
        P.COT,
        P.ADDRSS_LINE2,P.ADDRSS_LINE1,P.ADDRSS_LINE3,P.ADDRSS_LINE4,P.CITY,P.STATE,P.ZIP,
        P.HIN,
        P.DEA,
        P.DEA_EXP_DATE,
        P.PRICE_SOURCE_PCCA,
        P.BID_OR_PRCA,
        P.BID_OR_PRCA_NAME,
        P.LPG_ID,
        P.LPG_DESC,
        P.CURR_PRC_SRC,
        P.CURR_PRC_SRC_NAME,
        P.BL_CNTRCT_END_DT,
        P.PCCA_CNCTD,
        P.VRCST_CONT_EXCLD,
        avg(P.PRCNT_CNCTD) as AVG_PRCNT_CNCTD,
        SUM(P.ACTL_NEG_M) as SUM_ACTL_NEG_M,
        SUM(P.PROJ_NEG_M) as SUM_PROJ_NEG_M,
        SUM(P.ACTL_GP) as SUM_ACTL_GP,
        SUM(P.PROJ_GP) as SUM_PROJ_GP,
        SUM(P.PNDG_MMR_OPP) as SUM_PNDG_MMR_OPP,
        SUM(P.RES_MMR_OPP)  as SUM_RES_MMR_OPP,
        P.DECISION_MAKER,
        P.ACCT_MGR_NAME 
FROM  MRGN_EU.PAL_RPA P 
WHERE   P.TEAM_ASSIGNED = 'STRAT' 
    AND P.CASE_CNTR IN ('223') 
    AND P.MMR_TYPE = 'VC' 
    AND P.INSRT_DT > SYSDATE-14 
    and P.MN_LPG_PRCA_COST is not null
GROUP BY P.MMR_CASE, P.SYS_PLTFRM, P.BUS_PLTFRM, P.POOL_NUM, P.POOL_NAME, P.VENDOR_NAME, P.CURR_MCK_CONT, P.CURR_MFG_CONT, P.CURR_MFG_CONT_NAME, P.CURR_CONT_TYPE, P.VRCST_ORGN_SCR, P.VRCST_MFG_CONT, P.VRCST_MCK_CONT, P.VAR_CST_CONT_NAME, P.VAR_CST_CONT_TYPE, P.VRCST_CONT_ATR_ELIG_FLG, P.VRCST_CONT_TIER_BASE_FLG, P.VRCST_GPO_NAME, P.GPO_COT, P.GPO_COT_NAME, P.PRMRY_GPO_FLAG, P.PRMRY_GPO_NAME, P.PRMRY_GPO_ID, P.GPO_MMBRSHP_ST, P.PRMRY_AFF_ST, P.RX_GPO_NAME, P.RX_GPO_ID, P.ACCT_OR_BILL_TO, P.ACCT_OR_BILL_TO_NAME, P.SHIP_TO, P.ST_NAME, P.COT, P.ADDRSS_LINE2, P.ADDRSS_LINE1, P.ADDRSS_LINE3, P.ADDRSS_LINE4, P.CITY, P.STATE, P.ZIP, P.HIN, P.DEA, P.DEA_EXP_DATE, P.PRICE_SOURCE_PCCA, P.BID_OR_PRCA, P.BID_OR_PRCA_NAME, P.LPG_ID, P.LPG_DESC, P.CURR_PRC_SRC, P.CURR_PRC_SRC_NAME, P.BL_CNTRCT_END_DT, P.PCCA_CNCTD, P.VRCST_CONT_EXCLD, P.DECISION_MAKER, P.ACCT_MGR_NAME;--END REGION

--REGION strat contract cost increases FOR EXCEL
SELECT DISTINCT P.ACCT_ITEM_KEY,
                P.SYS_PLTFRM,
                P.BUS_PLTFRM,
                P.HIGHEST_CUST_NAME,
                P.ACCT_OR_BILL_TO,
                P.ACCT_OR_BILL_TO_NAME,
                P.SHIP_TO,
                P.ST_NAME,
                P.COT,
                P.ITEM_AS400_NUM,
                P.ITEM_E1_NUM,
                P.COST_IMPACT,
                P.BL_DATE,
                P.BL_REASON_CD,
                P.BL_EXPLANATION,
                P.BL_COST,
                P.CURR_COST,
                P.BL_MCK_CONT,
                P.BL_MFG_CONT,
                P.BL_MFG_CONT_NAME,
                P.BL_CONT_TYPE,
                P.CURR_MCK_CONT,
                P.CURR_MFG_CONT,
                P.CURR_MFG_CONT_NAME,
                P.CURR_CONT_TYPE,
                P.BL_CNTRCT_END_DT,
                P.BL_CUST_ELIG_END_DT_MCK,
                P.BL_ITEM_END_DT,
                P.Prmry_GPO_Name,
                P.BL_SELL_PRICE,
                P.CURR_SELL_PRICE,
                P.BL_MARGIN_PERC,
                P.CURR_MARGIN_PERC,
                P.BL_PRC_RULE,
                P.CURR_PRC_RULE,
                P.DECISION_MAKER,
                P.BL_QTY,
                P.SELL_UOM,
                P.VENDOR_NAME,
                P.VENDOR_NUM,
                P.PRVT_BRND_FLG,
                P.CTLG_NUM,
                P.ITEM_DSC,
                P.ITEM_PRODUCT_FAM_DSC,
                P.ACTL_NEG_M,
                P.PROJ_NEG_M,
                P.PNDG_MMR_OPP,
                P.ACTL_GP,
                P.PROJ_GP,
                CASE WHEN P.CASE_CNTR > 70 THEN 'ITEM' ELSE 'CONTRACT' END AS INCRS_TYPE,
                P.CURR_CHANGE_SUMMARY,
                P.MMR_CASE,
                P.CASE_CNTR 
FROM MRGN_EU.PAL_RPA P 
WHERE P.TEAM_ASSIGNED='STRAT' 
    AND P.CASE_CNTR IN ('559') 
  AND P.MMR_TYPE in('CCI','CCI/LM') 
  AND P.INSRT_DT>SYSDATE-14 
GROUP BY P.ACCT_ITEM_KEY, P.SYS_PLTFRM, P.BUS_PLTFRM, P.HIGHEST_CUST_NAME, P.ACCT_OR_BILL_TO, P.ACCT_OR_BILL_TO_NAME, P.SHIP_TO, P.ST_NAME, P.COT, P.ITEM_AS400_NUM, P.ITEM_E1_NUM, P.COST_IMPACT, P.BL_DATE, P.BL_REASON_CD, P.BL_EXPLANATION, P.BL_COST, P.CURR_COST, P.BL_MCK_CONT, P.BL_MFG_CONT, P.BL_MFG_CONT_NAME, P.BL_CONT_TYPE, P.BL_CNTRCT_END_DT, P.BL_CUST_ELIG_END_DT_MCK, P.BL_ITEM_END_DT, P.CURR_MCK_CONT, P.CURR_MFG_CONT, P.CURR_MFG_CONT_NAME, P.CURR_CONT_TYPE, P.Prmry_GPO_Name, P.BL_SELL_PRICE, P.CURR_SELL_PRICE, P.BL_MARGIN_PERC, P.CURR_MARGIN_PERC, P.BL_PRC_RULE, P.CURR_PRC_RULE, P.DECISION_MAKER, P.BL_QTY, P.SELL_UOM, P.VENDOR_NAME, P.VENDOR_NUM, P.PRVT_BRND_FLG, P.CTLG_NUM, P.ITEM_DSC, P.ITEM_PRODUCT_FAM_DSC, P.ACTL_NEG_M, P.PROJ_NEG_M, P.PNDG_MMR_OPP, P.ACTL_GP, P.PROJ_GP, P.CURR_CHANGE_SUMMARY, P.MMR_CASE, P.CASE_CNTR
ORDER BY P.CASE_CNTR
 ;--END REGION

--REGION acq cost
SELECT DISTINCT P.MMR_CASE,
                P.ACCT_ITEM_KEY,
                P.SYS_PLTFRM,
                P.BUS_PLTFRM,
                P.BID_OR_PRCA,
                P.BID_OR_PRCA_NAME,
                P.LPG_ID,
                P.LPG_DESC,
                P.HIGHEST_CUST_NAME,
                P.ACCT_OR_BILL_TO,
                P.ACCT_OR_BILL_TO_NAME,
                P.SHIP_TO,
                P.ST_NAME,
                P.COT,
                P.ITEM_AS400_NUM,
                P.ITEM_E1_NUM,
                P.ITEM_DSC,
                P.VENDOR_NAME,
                P.BL_QTY,
                P.BL_DATE,
                P.BL_COST,
                P.CURR_COST,
                P.BL_COMP_COST,
                P.CURR_COMP_COST,
                P.BL_SELL_PRICE,
                P.CURR_SELL_PRICE,
                P.BL_PRC_RULE,
                P.CURR_PRC_RULE,
                P.BL_MARGIN_PERC,
                P.CURR_MARGIN_PERC,
                P.PRMRY_GPO_NAME,
                P.PNDG_MMR_OPP
FROM MRGN_EU.PAL_RPA P 
WHERE P.TEAM_ASSIGNED = 'STRAT' 
    AND P.CASE_CNTR IN ('223') 
  AND P.MMR_TYPE in ('CI','CI/LM') 
  AND P.INSRT_DT > SYSDATE-14 
  and P.PNDG_MMR_OPP > 0 
ORDER BY P.CASE_CNTR;--END REGION
          
--region low margin
SELECT DISTINCT P.ACCT_ITEM_KEY,
                P.MMR_CASE,
                P.SYS_PLTFRM,
                P.BUS_PLTFRM,
                P.BID_OR_PRCA,
                P.BID_OR_PRCA_NAME,
                P.LPG_ID,
                P.LPG_DESC,
                P.HIGHEST_CUST_NAME,
                P.ACCT_OR_BILL_TO,
                P.ACCT_OR_BILL_TO_NAME,
                P.SHIP_TO,
                P.ST_NAME,
                P.COT,
                P.ITEM_AS400_NUM,
                P.ITEM_E1_NUM,
                P.ITEM_DSC,
                P.VENDOR_NAME,
                P.BL_QTY,
                P.BL_DATE,
                P.BL_COST,
                P.CURR_COST,
                P.BL_COMP_COST,
                P.CURR_COMP_COST,
                P.BL_SELL_PRICE,
                P.CURR_SELL_PRICE,
                P.BL_MARGIN_PERC,
                P.CURR_MARGIN_PERC,
                P.BL_PRC_RULE,
                P.CURR_PRC_RULE,
                P.PRMRY_GPO_NAME,
                P.PNDG_MMR_OPP
FROM MRGN_EU.PAL_RPA P
WHERE P.TEAM_ASSIGNED = 'STRAT' --PICK YOUR TEAM HERE
    AND P.CASE_CNTR IN ('223') 
      AND P.MMR_TYPE in ('LM')    --PICK YOUR BUCKET HERE
      AND P.INSRT_DT > SYSDATE -14
      and P.PNDG_MMR_OPP > 0; --END REGION

------------------------------------------------------------
--4 FOR NM--
------------------------------------------------------------

--REGION var cost for excel 
SELECT  P.MMR_CASE,
        P.SYS_PLTFRM,
        P.BUS_PLTFRM,
        P.POOL_NUM,
        P.POOL_NAME,
        P.VENDOR_NAME,
        P.CURR_MCK_CONT,
        P.CURR_MFG_CONT,
        P.CURR_MFG_CONT_NAME,
        P.CURR_CONT_TYPE,
        P.VRCST_ORGN_SCR,
        P.VRCST_MCK_CONT,
        P.VRCST_MFG_CONT,  
        P.VAR_CST_CONT_NAME,
        P.VAR_CST_CONT_TYPE,
        P.VRCST_CONT_ATR_ELIG_FLG,
        P.VRCST_CONT_TIER_BASE_FLG,
        P.VRCST_GPO_NAME,
        P.GPO_COT,
        P.GPO_COT_NAME,
        P.PRMRY_GPO_FLAG,
        P.PRMRY_GPO_NAME,
        P.PRMRY_GPO_ID,
        P.GPO_MMBRSHP_ST,
        P.PRMRY_AFF_ST,
        P.RX_GPO_NAME,
        P.RX_GPO_ID,
        P.ACCT_OR_BILL_TO,
        P.ACCT_OR_BILL_TO_NAME,
        P.SHIP_TO,
        P.ST_NAME,
        P.COT,
        P.ADDRSS_LINE2,P.ADDRSS_LINE1,P.ADDRSS_LINE3,P.ADDRSS_LINE4,P.CITY,P.STATE,P.ZIP,
        P.HIN,
        P.DEA,
        P.DEA_EXP_DATE,
        P.PRICE_SOURCE_PCCA,
        P.BID_OR_PRCA,
        P.BID_OR_PRCA_NAME,
        P.LPG_ID,
        P.LPG_DESC,
        P.CURR_PRC_SRC,
        P.CURR_PRC_SRC_NAME,
        P.BL_CNTRCT_END_DT,
        P.PCCA_CNCTD,
        P.VRCST_CONT_EXCLD,
        avg(P.PRCNT_CNCTD) as AVG_PRCNT_CNCTD,
        SUM(P.ACTL_NEG_M) as SUM_ACTL_NEG_M,
        SUM(P.PROJ_NEG_M) as SUM_PROJ_NEG_M,
        SUM(P.ACTL_GP) as SUM_ACTL_GP,
        SUM(P.PROJ_GP) as SUM_PROJ_GP,
        SUM(P.PNDG_MMR_OPP) as SUM_PNDG_MMR_OPP,
        SUM(P.RES_MMR_OPP)  as SUM_RES_MMR_OPP,
        P.DECISION_MAKER,
        P.ACCT_MGR_NAME 
FROM MRGN_EU.PAL_RPA P 
WHERE P.TEAM_ASSIGNED = 'NM' --PICK YOUR TEAM HERE
      AND P.CASE_CNTR = 1       --PICK YOUR POOL HERE
      AND P.MMR_TYPE = 'VC'    --PICK YOUR BUCKET HERE
      AND P.INSRT_DT > SYSDATE -14
      AND P.MN_LPG_PRCA_COST is not null
GROUP BY P.MMR_CASE, P.TEAM_ASSIGNED, P.SYS_PLTFRM, P.BUS_PLTFRM, P.POOL_NUM, P.POOL_NAME, P.VENDOR_NAME, P.CURR_MCK_CONT, P.CURR_MFG_CONT, P.CURR_MFG_CONT_NAME, P.CURR_CONT_TYPE, P.VRCST_ORGN_SCR, P.VRCST_MFG_CONT, P.VRCST_MCK_CONT, P.VAR_CST_CONT_NAME, P.VAR_CST_CONT_TYPE, P.VRCST_CONT_ATR_ELIG_FLG, P.VRCST_CONT_TIER_BASE_FLG, P.VRCST_GPO_NAME, P.GPO_COT, P.GPO_COT_NAME, P.PRMRY_GPO_FLAG, P.PRMRY_GPO_NAME, P.PRMRY_GPO_ID, P.GPO_MMBRSHP_ST, P.PRMRY_AFF_ST, P.RX_GPO_NAME, P.RX_GPO_ID, P.ACCT_OR_BILL_TO, P.ACCT_OR_BILL_TO_NAME, P.SHIP_TO, P.ST_NAME, P.COT, P.ADDRSS_LINE2, P.ADDRSS_LINE1, P.ADDRSS_LINE3, P.ADDRSS_LINE4, P.CITY, P.STATE, P.ZIP, P.HIN, P.DEA, P.DEA_EXP_DATE, P.PRICE_SOURCE_PCCA, P.BID_OR_PRCA, P.BID_OR_PRCA_NAME, P.LPG_ID, P.LPG_DESC, P.CURR_PRC_SRC, P.CURR_PRC_SRC_NAME, P.BL_CNTRCT_END_DT, P.PCCA_CNCTD, P.VRCST_CONT_EXCLD, P.DECISION_MAKER, P.ACCT_MGR_NAME
;--END REGION

--REGION NM contract cost increases FOR EXCEL
SELECT DISTINCT P.ACCT_ITEM_KEY,
                P.SYS_PLTFRM,
                P.BUS_PLTFRM,
                P.HIGHEST_CUST_NAME,
                P.ACCT_OR_BILL_TO,
                P.ACCT_OR_BILL_TO_NAME,
                P.SHIP_TO,
                P.ST_NAME,
                P.ADDRSS_LINE2,P.ADDRSS_LINE1,P.ADDRSS_LINE3,P.ADDRSS_LINE4,P.CITY,P.STATE,P.ZIP,
                P.ITEM_AS400_NUM,
                P.ITEM_E1_NUM,
                P.COST_IMPACT,
                P.BL_DATE,
                P.BL_REASON_CD,
                P.BL_EXPLANATION,
                P.BL_COST,
                P.CURR_COST,
                P.BL_MCK_CONT,
                P.BL_MFG_CONT,
                P.BL_MFG_CONT_NAME,
                P.BL_CONT_TYPE,
                P.BL_CNTRCT_END_DT,
                P.BL_CUST_ELIG_END_DT_MCK,
                P.BL_ITEM_END_DT,
                P.CURR_MCK_CONT,
                P.CURR_MFG_CONT,
                P.CURR_MFG_CONT_NAME,
                P.CURR_CONT_TYPE,
                P.BL_CUST_PRIM_GPO_NUM,
                P.CURR_CUST_PRIM_GPO_NUM,
                P.BL_SELL_PRICE,
                P.CURR_SELL_PRICE,
                P.BL_MARGIN_PERC,
                P.CURR_MARGIN_PERC,
                P.BL_PRC_RULE,
                P.CURR_PRC_RULE,
                P.DECISION_MAKER,
                P.BL_QTY,
                P.SELL_UOM,
                P.VENDOR_NAME,
                P.VENDOR_NUM,
                P.PRVT_BRND_FLG,
                P.CTLG_NUM,
                P.ITEM_DSC,
                P.ITEM_PRODUCT_FAM_DSC,
                P.PRMRY_GPO_NAME, 
                P.PRMRY_GPO_ID,
                P.ACTL_NEG_M,
                P.PROJ_NEG_M,
                P.PNDG_MMR_OPP,
                P.ACTL_GP,
                P.PROJ_GP,
                P.CURR_CHANGE_SUMMARY,
                P.MMR_CASE,
                P.CASE_CNTR,
                P.DECISION_MAKER,
                P.ACCT_MGR_NAME
FROM MRGN_EU.PAL_RPA P
WHERE P.TEAM_ASSIGNED = 'NM' --PICK YOUR TEAM HERE
      AND P.CASE_CNTR = 1    --POOL HERE
      AND P.MMR_TYPE in ('CCI','CCI/LM')    --PICK YOUR BUCKET HERE
      AND P.INSRT_DT > SYSDATE -14;--END REGION
      
--REGION acq cost
SELECT DISTINCT P.ACCT_ITEM_KEY,
                P.SYS_PLTFRM,
                P.BUS_PLTFRM,
                P.BID_OR_PRCA,
                P.BID_OR_PRCA_NAME,
                P.LPG_ID,
                P.LPG_DESC,
                P.HIGHEST_CUST_NAME,
                P.ACCT_OR_BILL_TO,
                P.ACCT_OR_BILL_TO_NAME,
                P.SHIP_TO,
                P.ST_NAME,
                P.ADDRSS_LINE2,P.ADDRSS_LINE1,P.ADDRSS_LINE3,P.ADDRSS_LINE4,P.CITY,P.STATE,P.ZIP,
                P.ITEM_AS400_NUM,
                P.ITEM_E1_NUM,
                P.ITEM_DSC,
                P.VENDOR_NAME,
                P.PRMRY_GPO_NAME, 
                P.PRMRY_GPO_ID,
                P.BL_QTY,
                P.PNDG_MMR_OPP,
                P.BL_DATE,
                P.BL_COST,
                P.CURR_COST,
                P.BL_COMP_COST,
                P.CURR_COMP_COST,
                P.BL_SELL_PRICE,
                P.CURR_SELL_PRICE,
                P.BL_MARGIN_PERC,
                P.CURR_MARGIN_PERC,
                P.BL_PRC_RULE,
                P.CURR_PRC_RULE,
                P.MMR_CASE,
                P.DECISION_MAKER,
                P.ACCT_MGR_NAME
FROM MRGN_EU.PAL_RPA P
WHERE P.TEAM_ASSIGNED = 'NM' --PICK YOUR TEAM HERE
      AND P.CASE_CNTR = 1  --PICK YOUR POOL HERE
      AND P.MMR_TYPE in ('CI','CI/LM')    --PICK YOUR BUCKET HERE
      AND P.INSRT_DT > SYSDATE -14
      and P.PNDG_MMR_OPP > 0;--END REGION
           
--region low margin
SELECT DISTINCT P.ACCT_ITEM_KEY,
                P.SYS_PLTFRM,
                P.BUS_PLTFRM,
                P.BID_OR_PRCA,
                P.BID_OR_PRCA_NAME,
                P.LPG_ID,
                P.LPG_DESC,
                P.HIGHEST_CUST_NAME,
                P.ACCT_OR_BILL_TO,
                P.ACCT_OR_BILL_TO_NAME,
                P.SHIP_TO,
                P.ST_NAME,
                P.ADDRSS_LINE2,P.ADDRSS_LINE1,P.ADDRSS_LINE3,P.ADDRSS_LINE4,P.CITY,P.STATE,P.ZIP,
                P.ITEM_AS400_NUM,
                P.ITEM_E1_NUM,
                P.ITEM_DSC,
                P.VENDOR_NAME,
                P.PRMRY_GPO_NAME, 
                P.PRMRY_GPO_ID,
                P.BL_QTY,
                P.PNDG_MMR_OPP,
                P.BL_DATE,
                P.BL_COST,
                P.CURR_COST,
                P.BL_COMP_COST,
                P.CURR_COMP_COST,
                P.BL_SELL_PRICE,
                P.CURR_SELL_PRICE,
                P.BL_MARGIN_PERC,
                P.CURR_MARGIN_PERC,
                P.BL_PRC_RULE,
                P.CURR_PRC_RULE,
                P.MMR_CASE,
                P.DECISION_MAKER,
                P.ACCT_MGR_NAME
FROM MRGN_EU.PAL_RPA P
WHERE P.TEAM_ASSIGNED = 'NM' --PICK YOUR TEAM HERE
      AND P.CASE_CNTR =1    --PICK YOUR POOL HERE
      AND P.MMR_TYPE in ('LM')    --PICK YOUR BUCKET HERE
      AND P.INSRT_DT > SYSDATE -14
      and P.PNDG_MMR_OPP > 0; --END REGION

------------------------------------------------------------
--1 FOR CCT--
------------------------------------------------------------

 --REGION cct FOR EXCEL
SELECT DISTINCT P.SYS_PLTFRM,
                P.BUS_PLTFRM,
                P.HIGHEST_CUST_NAME,
                P.ACCT_OR_BILL_TO,
                P.ACCT_OR_BILL_TO_NAME,
                P.SHIP_TO,
                P.ST_NAME,
                P.BID_OR_PRCA,
                P.PRICE_SOURCE_PCCA,
                P.COT,
                P.ADDRSS_LINE1,
                P.ADDRSS_LINE2,
                P.ADDRSS_LINE3,
                P.ADDRSS_LINE4,
                P.CITY,
                P.STATE,
                P.ZIP,
                P.ITEM_AS400_NUM,
                P.ITEM_E1_NUM,
                P.BL_QTY,
                P.CURR_QTY,
                P.CTLG_NUM,
                P.SELL_UOM,
                P.BUY_UOM,
                P.VENDOR_NUM,
                P.VENDOR_NAME,
                P.PRVT_BRND_FLG,
                P.ITEM_DSC,
                P.ITEM_PRODUCT_FAM_DSC,
                P.BL_DATE,
                P.CURR_DATE,
                P.BL_REASON_CD,
                P.BL_EXPLANATION,
                P.BL_CHANGE_SUMMARY,
                P.CURR_CHANGE_SUMMARY,
                P.BL_COST,
                P.CURR_COST,
                P.BL_COMP_COST,
                P.CURR_COMP_COST,
                P.BL_PRICING_COST,
                P.CURR_PRICING_COST,
                P.COST_IMPACT,
                P.BL_SELL_PRICE,
                P.CURR_SELL_PRICE,
                P.BL_PRC_RULE,
                P.CURR_PRC_RULE,
                P.BL_MARGIN_PERC,
                P.CURR_MARGIN_PERC,
                P.ACTL_NEG_M,
                P.PROJ_NEG_M,
                P.ACTL_GP,
                P.PROJ_GP,
                P.BL_MCK_CONT,
                P.BL_MFG_CONT,
                P.BL_MFG_CONT_NAME,
                P.BL_CONT_TYPE,
                P.CURR_MCK_CONT,
                P.CURR_MFG_CONT,
                P.CURR_MFG_CONT_NAME,
                P.CURR_CONT_TYPE,
                P.BL_CONT_ATR_ELIG_FLG,
                P.BL_CONT_TIER_BASE_FLG,
                P.CURR_CONT_ATR_ELIG_FLG,
                P.CURR_CONT_TIER_BASE_FLG,
                P.BL_ITEM_END_DT,
                P.BL_CNTRCT_END_DT,
                P.BL_CUST_ELIG_END_DT_MCK,
                P.CURR_ORGN_SCR,
                P.HIN,
                P.DEA,
                P.DEA_EXP_DATE,
                P.PRMRY_GPO_NAME,
                P.PRMRY_GPO_ID,
                P.RX_GPO_NAME,
                P.RX_GPO_ID,
                P.DECISION_MAKER,
                P.PNDG_MMR_OPP,
                P.POOL_NUM,
                P.MMR_CASE,
                P.CASE_CNTR,
                P.POOL_NAME,
                CASE WHEN P.CASE_CNTR > 70 THEN 'ITEM' ELSE 'CONTRACT' END AS INCRS_TYPE
FROM MRGN_EU.PAL_RPA P
WHERE P.TEAM_ASSIGNED = 'CCT'
      AND P.CASE_CNTR = '1'    
      AND P.INSRT_DT > SYSDATE -14
;--END REGION



SELECT DISTINCT P.ACCT_ITEM_KEY,
                P.SYS_PLTFRM,
                P.BUS_PLTFRM,
                P.HIGHEST_CUST_NAME,
                P.ACCT_OR_BILL_TO,
                P.ACCT_OR_BILL_TO_NAME,
                P.SHIP_TO,
                P.ST_NAME,
                P.ADDRSS_LINE2,P.ADDRSS_LINE1,P.ADDRSS_LINE3,P.ADDRSS_LINE4,P.CITY,P.STATE,P.ZIP,
                P.ITEM_AS400_NUM,
                P.ITEM_E1_NUM,
                P.COST_IMPACT,
                P.BL_DATE,
                P.BL_REASON_CD,
                P.BL_EXPLANATION,
                P.BL_COST,
                P.CURR_COST,
                P.BL_MCK_CONT,
                P.BL_MFG_CONT,
                P.BL_MFG_CONT_NAME,
                P.BL_CONT_TYPE,
                P.BL_CNTRCT_END_DT,
                P.BL_CUST_ELIG_END_DT_MCK,
                P.BL_ITEM_END_DT,
                P.CURR_MCK_CONT,
                P.CURR_MFG_CONT,
                P.CURR_MFG_CONT_NAME,
                P.CURR_CONT_TYPE,
                P.BL_CUST_PRIM_GPO_NUM,
                P.CURR_CUST_PRIM_GPO_NUM,
                P.BL_SELL_PRICE,
                P.CURR_SELL_PRICE,
                P.BL_MARGIN_PERC,
                P.CURR_MARGIN_PERC,
                P.BL_PRC_RULE,
                P.CURR_PRC_RULE,
                P.DECISION_MAKER,
                P.BL_QTY,
                P.SELL_UOM,
                P.VENDOR_NAME,
                P.VENDOR_NUM,
                P.PRVT_BRND_FLG,
                P.CTLG_NUM,
                P.ITEM_DSC,
                P.ITEM_PRODUCT_FAM_DSC,
                P.PRMRY_GPO_NAME, 
                P.PRMRY_GPO_ID,
                P.ACTL_NEG_M,
                P.PROJ_NEG_M,
                P.PNDG_MMR_OPP,
                P.ACTL_GP,
                P.PROJ_GP,
                P.CURR_CHANGE_SUMMARY,
                P.MMR_CASE,
                P.CASE_CNTR,
                P.DECISION_MAKER,
                P.ACCT_MGR_NAME
FROM MRGN_EU.PAL_RPA P
WHERE P.TEAM_ASSIGNED = 'NM' --PICK YOUR TEAM HERE
      AND P.CASE_CNTR < 10    --POOL HERE
      AND P.MMR_TYPE in ('CCI','CCI/LM')    --PICK YOUR BUCKET HERE
      AND P.INSRT_DT > SYSDATE -14;
      
      SELECT * FROM MRGN_EU.PAL_RPA;
      ;
