--REGION Min VAR_CST Details
SUB1 AS (SELECT DISTINCT PRICE_SOURCE, ITEM_AS400_NUM, a.ITEM_E1_NUM, PARNT_SUPLR_NUM,
                         CASE WHEN SYS_PLTFRM = 'AS400' THEN ITEM_AS400_NUM ELSE TO_CHAR(a.ITEM_E1_NUM) END AS ITEM,
                         CASE WHEN SYS_PLTFRM = 'E1' THEN LEAST(COMP_COST_INITIAL, PRICING_COST_INITIAL) ELSE COMP_COST_INITIAL END AS LPG_PRCA_Cost,
                         CASE WHEN SYS_PLTFRM = 'E1' AND PRICING_COST_INITIAL < COMP_COST_INITIAL THEN PRICING_COST_CONT_ID ELSE COMP_COST_CONT_ID END AS VAR_CST_CONT,
                         CASE WHEN SYS_PLTFRM = 'E1' AND PRICING_COST_INITIAL < COMP_COST_INITIAL THEN PRICING_COST_LIST_ID ELSE COMP_COST_LIST_ID END AS VAR_CST_CONT_ID,
                         CASE WHEN SYS_PLTFRM = 'E1' AND PRICING_COST_INITIAL < COMP_COST_INITIAL THEN PRICING_COST_CONT_NAME ELSE COMP_COST_CONT_NAME END AS VAR_CST_CONT_NAME,
                         CASE WHEN SYS_PLTFRM = 'E1' AND PRICING_COST_INITIAL < COMP_COST_INITIAL THEN PRICING_COST_CONT_TYPE ELSE COMP_COST_CONT_TYPE END AS VAR_CST_CONT_TYPE     
         FROM MRGN_EU.HAH_IPC a
         LEFT JOIN EDWRPT.V_DIM_ITEM_E1_CURR b ON a.ITEM_E1_NUM = b.ITEM_E1_NUM
         WHERE VAR_COST = 'Y'),
SUB2 AS (SELECT DISTINCT PRICE_SOURCE, 
                         CASE WHEN SYS_PLTFRM = 'AS400' THEN ITEM_AS400_NUM ELSE TO_CHAR(ITEM_E1_NUM) END AS ITEM,
                         CASE WHEN SYS_PLTFRM = 'AS400' THEN MIN(COMP_COST_INITIAL) OVER (PARTITION BY PRICE_SOURCE, ITEM_AS400_NUM)  
                              WHEN SYS_PLTFRM = 'E1' THEN MIN(LEAST(COMP_COST_INITIAL, PRICING_COST_INITIAL)) OVER (PARTITION BY PRICE_SOURCE, ITEM_E1_NUM) END AS Mn_LPG_PRCA_Cost
         FROM MRGN_EU.HAH_IPC
         WHERE VAR_COST = 'Y'),
SUB3 AS (SELECT (sub1.PRICE_SOURCE || ',' || sub1.ITEM) as PRC_SRC_ITEM_KEY, sub1.PARNT_SUPLR_NUM,
                 sub2.Mn_LPG_PRCA_Cost, sub1.VAR_CST_CONT, sub1.VAR_CST_CONT_ID, sub1.VAR_CST_CONT_NAME, sub1.VAR_CST_CONT_TYPE, 
                 RANK() OVER (PARTITION BY sub1.PRICE_SOURCE, sub1.ITEM ORDER BY sub1.VAR_CST_CONT, VAR_CST_CONT_ID, sub1.VAR_CST_CONT_TYPE, sub1.VAR_CST_CONT_NAME) as RNK
         FROM sub1
         INNER JOIN sub2 ON sub1.PRICE_SOURCE = sub2.PRICE_SOURCE 
                        AND sub1.ITEM = sub2.ITEM
                        AND sub1.LPG_PRCA_Cost = sub2.Mn_LPG_PRCA_Cost), 
VCST AS (SELECT sub3.*, gpo.GPO_NUM as VAR_CST_GPO_NUM, gpo.GPO_NAME as VAR_CST_GPO_NAME 
         FROM      sub3
         LEFT JOIN EDWRPT.V_DIM_CNTRCT_TIER cntt ON sub3.VAR_CST_CONT_ID = (cntt.CNTRCT_NUM ||'-'|| cntt.TIER_NUM) AND sub3.VAR_CST_CONT_TYPE = cntt.CNTRCT_TYPE_CD AND cntt.CNTRCT_END_DT > SYSDATE
         LEFT JOIN EDWRPT.V_DIM_GPO gpo ON gpo.DIM_GPO_ID = cntt.DIM_GPO_ID AND gpo.GPO_END_DT > SYSDATE
         WHERE sub3.RNK = 1), --END REGION
